name: Continuous Integration Checks

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build src --configuration Release --no-restore

    - name: Test
      run: dotnet test src --configuration Release --no-build --verbosity normal
